//! # nether_rt_array
//!
//! Purpose: the `Array<T>` heap type's storage and operations
//! (`docs/architecture/crates.md` § `runtime/array`).
//!
//! Responsibilities: contiguous growable storage behind
//! [`nether_rt_arc`]'s refcounted header; `push`/`pop`/`len`/`get`;
//! element retain/release on mutation, since an element of a heap `T` is
//! itself ARC-managed (`arc-model.md` §1).
//!
//! This crate is generic only over element *size* (monomorphized per
//! concrete `T` at the `nether_codegen` level, per `crates.md`'s own
//! note) — it has no idea what `T` actually is. So `nether_rt_array_new`
//! takes two optional callback pointers, `elem_retain`/`elem_drop`,
//! generated by `nether_codegen` per concrete `T` (see its `shims`
//! module): `None` if `T` has no heap-kind content at all (a plain
//! `Array<i64>` never calls either), otherwise a function taking one
//! element's own slot address inside this array's buffer.
//!
//! - [`nether_rt_array_push`] calls `elem_retain` (if any) on the just
//!   -copied slot — this is this crate's *own* retain, making the array
//!   an independent owner of whatever it was just handed (mirroring how
//!   a field *store* retains its new value, `arc-model.md` §3.1); the
//!   transient retain/release `nether_mir`'s ARC pass wraps around every
//!   call argument (including this one) nets to zero and does not, on
//!   its own, grant the array any lasting reference.
//! - [`nether_rt_array_pop`] calls neither: the popped element's
//!   ownership transfers whole to the caller's fresh binding (this
//!   crate's own credit for it is given up, not released), matching
//!   every other call result's "arrives already owned" convention.
//! - The array's own drop (see `drop_buffer`, run once its own refcount
//!   reaches zero) calls `elem_drop` on every remaining element, then
//!   frees the buffer.
//!
//! Dependencies: `nether_rt_arc`.
//!
//! Consumers: generated code for any `Array<T>`-typed expression.
//!
//! Invariants: element retain/release is always balanced with the
//! array's own lifetime and mutation operations.

use nether_rt_arc::nether_rt_arc_alloc;

type ElemFn = Option<extern "C" fn(*mut u8)>;

/// An `Array<T>`'s payload: an owned, plain (not itself refcounted)
/// growable byte buffer holding `len` elements of `elem_size` bytes
/// each, plus the two callbacks needed to keep each element's own
/// ownership correct (see module docs).
#[repr(C)]
struct ArrayRepr {
    ptr: *mut u8,
    len: i64,
    cap: i64,
    elem_size: i64,
    elem_retain: ElemFn,
    elem_drop: ElemFn,
}

fn buf_layout(elem_size: i64, cap: i64) -> std::alloc::Layout {
    let bytes = usize::try_from(elem_size).unwrap_or(0) * usize::try_from(cap).unwrap_or(0);
    std::alloc::Layout::from_size_align(bytes.max(1), 16)
        .expect("nether_rt_array: invalid buffer size")
}

extern "C" fn drop_buffer(payload: *mut u8) {
    unsafe {
        let r = &*payload.cast::<ArrayRepr>();
        if let Some(elem_drop) = r.elem_drop {
            for i in 0..r.len {
                elem_drop(r.ptr.add(usize::try_from(i * r.elem_size).unwrap_or(0)));
            }
        }
        std::alloc::dealloc(r.ptr, buf_layout(r.elem_size, r.cap));
    }
}

/// Builds a new, empty `Array<T>` with room for `cap` elements of
/// `elem_size` bytes each.
#[no_mangle]
pub extern "C" fn nether_rt_array_new(
    elem_size: i64,
    cap: i64,
    elem_retain: ElemFn,
    elem_drop: ElemFn,
) -> *mut u8 {
    let cap = cap.max(1);
    let layout = buf_layout(elem_size, cap);
    let ptr = unsafe {
        let p = std::alloc::alloc(layout);
        if p.is_null() {
            std::alloc::handle_alloc_error(layout);
        }
        p
    };
    let payload = nether_rt_arc_alloc(std::mem::size_of::<ArrayRepr>() as i64, Some(drop_buffer));
    unsafe {
        payload.cast::<ArrayRepr>().write(ArrayRepr {
            ptr,
            len: 0,
            cap,
            elem_size,
            elem_retain,
            elem_drop,
        });
    }
    payload
}

unsafe fn grow(r: &mut ArrayRepr) {
    let new_cap = (r.cap * 2).max(1);
    let old_layout = buf_layout(r.elem_size, r.cap);
    let new_layout = buf_layout(r.elem_size, new_cap);
    let new_ptr = std::alloc::alloc(new_layout);
    if new_ptr.is_null() {
        std::alloc::handle_alloc_error(new_layout);
    }
    std::ptr::copy_nonoverlapping(
        r.ptr,
        new_ptr,
        usize::try_from(r.len * r.elem_size).unwrap_or(0),
    );
    std::alloc::dealloc(r.ptr, old_layout);
    r.ptr = new_ptr;
    r.cap = new_cap;
}

/// Copies `elem_size` bytes from `elem` onto the end of `arr`'s storage,
/// growing it first if full, then retains the newly stored slot (see
/// module docs).
///
/// # Safety
/// `arr` must point at a live `Array<T>` object; `elem` must point at
/// `elem_size` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn nether_rt_array_push(arr: *mut u8, elem: *const u8) {
    unsafe {
        let r = &mut *arr.cast::<ArrayRepr>();
        if r.len == r.cap {
            grow(r);
        }
        let slot = r.ptr.add(usize::try_from(r.len * r.elem_size).unwrap_or(0));
        std::ptr::copy_nonoverlapping(elem, slot, r.elem_size as usize);
        if let Some(retain) = r.elem_retain {
            retain(slot);
        }
        r.len += 1;
    }
}

/// # Safety
/// `arr` must point at a live `Array<T>` object.
#[no_mangle]
pub unsafe extern "C" fn nether_rt_array_len(arr: *mut u8) -> i64 {
    unsafe { (*arr.cast::<ArrayRepr>()).len }
}

/// A pointer to element `index`'s own storage inside `arr`'s buffer —
/// the caller loads/stores through it directly, using its own static
/// knowledge of the element's LLVM type.
///
/// # Safety
/// `arr` must point at a live `Array<T>` object.
#[no_mangle]
pub unsafe extern "C" fn nether_rt_array_get(arr: *mut u8, index: i64) -> *mut u8 {
    unsafe {
        let r = &*arr.cast::<ArrayRepr>();
        assert!(
            index >= 0 && index < r.len,
            "nether_rt_array_get: index {index} out of bounds (len {})",
            r.len
        );
        r.ptr.add(usize::try_from(index * r.elem_size).unwrap_or(0))
    }
}

/// `0` (and leaves `out_elem` untouched) if `arr` is empty; otherwise
/// copies the last element into `out_elem` and returns `1` — see module
/// docs for why this does not itself retain or release anything.
///
/// # Safety
/// `arr` must point at a live `Array<T>` object; `out_elem` must point at
/// `elem_size` writable bytes.
#[no_mangle]
pub unsafe extern "C" fn nether_rt_array_pop(arr: *mut u8, out_elem: *mut u8) -> u8 {
    unsafe {
        let r = &mut *arr.cast::<ArrayRepr>();
        if r.len == 0 {
            return 0;
        }
        r.len -= 1;
        let slot = r.ptr.add(usize::try_from(r.len * r.elem_size).unwrap_or(0));
        std::ptr::copy_nonoverlapping(slot, out_elem, r.elem_size as usize);
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nether_rt_arc::nether_rt_arc_release;
    use std::sync::atomic::{AtomicI64, Ordering};

    #[test]
    fn push_len_get_pop_of_i64_elements() {
        unsafe {
            let arr = nether_rt_array_new(8, 2, None, None);
            for v in [10i64, 20, 30] {
                nether_rt_array_push(arr, (&v as *const i64).cast());
            }
            assert_eq!(nether_rt_array_len(arr), 3);
            assert_eq!(*nether_rt_array_get(arr, 0).cast::<i64>(), 10);
            assert_eq!(*nether_rt_array_get(arr, 2).cast::<i64>(), 30);

            let mut out: i64 = 0;
            let ok = nether_rt_array_pop(arr, (&mut out as *mut i64).cast());
            assert_eq!(ok, 1);
            assert_eq!(out, 30);
            assert_eq!(nether_rt_array_len(arr), 2);
            nether_rt_arc_release(arr);
        }
    }

    #[test]
    fn pop_on_empty_returns_zero() {
        unsafe {
            let arr = nether_rt_array_new(8, 1, None, None);
            let mut out: i64 = 0;
            assert_eq!(nether_rt_array_pop(arr, (&mut out as *mut i64).cast()), 0);
            nether_rt_arc_release(arr);
        }
    }

    static RETAINS: AtomicI64 = AtomicI64::new(0);
    static DROPS: AtomicI64 = AtomicI64::new(0);

    extern "C" fn track_retain(_slot: *mut u8) {
        RETAINS.fetch_add(1, Ordering::SeqCst);
    }
    extern "C" fn track_drop(_slot: *mut u8) {
        DROPS.fetch_add(1, Ordering::SeqCst);
    }

    #[test]
    fn push_retains_and_final_drop_releases_every_remaining_element() {
        unsafe {
            let retains_before = RETAINS.load(Ordering::SeqCst);
            let drops_before = DROPS.load(Ordering::SeqCst);
            let arr = nether_rt_array_new(8, 2, Some(track_retain), Some(track_drop));
            for v in [1i64, 2, 3] {
                nether_rt_array_push(arr, (&v as *const i64).cast());
            }
            assert_eq!(
                RETAINS.load(Ordering::SeqCst),
                retains_before + 3,
                "one retain per push"
            );

            let mut out: i64 = 0;
            nether_rt_array_pop(arr, (&mut out as *mut i64).cast());
            assert_eq!(
                DROPS.load(Ordering::SeqCst),
                drops_before,
                "pop must not drop the element it hands back"
            );

            nether_rt_arc_release(arr);
            assert_eq!(
                DROPS.load(Ordering::SeqCst),
                drops_before + 2,
                "final drop releases the two remaining elements, not the popped one"
            );
        }
    }
}
