[package]
name = "nether"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
nether-frontend = { path = "../compiler/frontend" }
nether-core = { path = "../compiler/core" }
nether-semantics = { path = "../compiler/semantics" }

[lints]
workspace = true
